### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by scavru** [Hukasx0/character-factory#19]
API connectivity to external sources such as openAI, oobabooga text-generation-webui, koboldccp and other OpenAI-compatible APIs.

**Comment by thijsi123** [comment]
You may take a look at my repository. (It's very wip and mostly used for testing.) Give me a few minutes to work some things out first before I push my changes.

**Comment by thijsi123** [comment]
There, don't expect too much of it. https://github.com/thijsi123/character-factory

most of it is a complete mess 😅

**Comment by scavru** [comment]
koboldcpp-webui.py and oobabooga - webui test fandom character.py connecting fine
It would be nice if they could integrate it into this project. In theory, there is no need for more than that.

**Comment by thijsi123** [comment]
Most definitely!

**Comment by Hukasx0** [comment]
Hello, sorry for the late reply as I have been quite busy over the last month.
When I created these scripts, I designed them with simplicity in mind. My goal was to make them easy to read and edit (for example to change or improve prompts easily), so I didn't want to complicate things by requiring users to tinker with configurations, code, flags, or environment variables just to run the script. That's why I didn't include support for external APIs, as it would add unnecessary complexity for users who just want to download and use the script. Besides, the prompts are tailored for the specific models that the script uses, and supporting external APIs (in my opinion) wouldn't add much value.
